// Copyright IBM Corp. 2016, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/plugin/grpc_broker.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     uint32                 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Knock         *ConnInfo_Knock        `protobuf:"bytes,4,opt,name=knock,proto3" json:"knock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnInfo) Reset() {
	*x = ConnInfo{}
	mi := &file_internal_plugin_grpc_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnInfo) ProtoMessage() {}

func (x *ConnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_grpc_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnInfo.ProtoReflect.Descriptor instead.
func (*ConnInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugin_grpc_broker_proto_rawDescGZIP(), []int{0}
}

func (x *ConnInfo) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ConnInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ConnInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConnInfo) GetKnock() *ConnInfo_Knock {
	if x != nil {
		return x.Knock
	}
	return nil
}

type ConnInfo_Knock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knock         bool                   `protobuf:"varint,1,opt,name=knock,proto3" json:"knock,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnInfo_Knock) Reset() {
	*x = ConnInfo_Knock{}
	mi := &file_internal_plugin_grpc_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnInfo_Knock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnInfo_Knock) ProtoMessage() {}

func (x *ConnInfo_Knock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_grpc_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnInfo_Knock.ProtoReflect.Descriptor instead.
func (*ConnInfo_Knock) Descriptor() ([]byte, []int) {
	return file_internal_plugin_grpc_broker_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnInfo_Knock) GetKnock() bool {
	if x != nil {
		return x.Knock
	}
	return false
}

func (x *ConnInfo_Knock) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *ConnInfo_Knock) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_plugin_grpc_broker_proto protoreflect.FileDescriptor

const file_internal_plugin_grpc_broker_proto_rawDesc = "" +
	"\n" +
	"!internal/plugin/grpc_broker.proto\x12\x06plugin\"\xd2\x01\n" +
	"\bConnInfo\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\rR\tserviceId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12,\n" +
	"\x05knock\x18\x04 \x01(\v2\x16.plugin.ConnInfo.KnockR\x05knock\x1aE\n" +
	"\x05Knock\x12\x14\n" +
	"\x05knock\x18\x01 \x01(\bR\x05knock\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2C\n" +
	"\n" +
	"GRPCBroker\x125\n" +
	"\vStartStream\x12\x10.plugin.ConnInfo\x1a\x10.plugin.ConnInfo(\x010\x01B.Z,github.com/arloliu/go-plugin/internal/pluginb\x06proto3"

var (
	file_internal_plugin_grpc_broker_proto_rawDescOnce sync.Once
	file_internal_plugin_grpc_broker_proto_rawDescData []byte
)

func file_internal_plugin_grpc_broker_proto_rawDescGZIP() []byte {
	file_internal_plugin_grpc_broker_proto_rawDescOnce.Do(func() {
		file_internal_plugin_grpc_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_grpc_broker_proto_rawDesc), len(file_internal_plugin_grpc_broker_proto_rawDesc)))
	})
	return file_internal_plugin_grpc_broker_proto_rawDescData
}

var file_internal_plugin_grpc_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_plugin_grpc_broker_proto_goTypes = []any{
	(*ConnInfo)(nil),       // 0: plugin.ConnInfo
	(*ConnInfo_Knock)(nil), // 1: plugin.ConnInfo.Knock
}
var file_internal_plugin_grpc_broker_proto_depIdxs = []int32{
	1, // 0: plugin.ConnInfo.knock:type_name -> plugin.ConnInfo.Knock
	0, // 1: plugin.GRPCBroker.StartStream:input_type -> plugin.ConnInfo
	0, // 2: plugin.GRPCBroker.StartStream:output_type -> plugin.ConnInfo
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_plugin_grpc_broker_proto_init() }
func file_internal_plugin_grpc_broker_proto_init() {
	if File_internal_plugin_grpc_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_grpc_broker_proto_rawDesc), len(file_internal_plugin_grpc_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_grpc_broker_proto_goTypes,
		DependencyIndexes: file_internal_plugin_grpc_broker_proto_depIdxs,
		MessageInfos:      file_internal_plugin_grpc_broker_proto_msgTypes,
	}.Build()
	File_internal_plugin_grpc_broker_proto = out.File
	file_internal_plugin_grpc_broker_proto_goTypes = nil
	file_internal_plugin_grpc_broker_proto_depIdxs = nil
}
