// Copyright IBM Corp. 2016, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/plugin/grpc_stdio.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StdioData_Channel int32

const (
	StdioData_INVALID StdioData_Channel = 0
	StdioData_STDOUT  StdioData_Channel = 1
	StdioData_STDERR  StdioData_Channel = 2
)

// Enum value maps for StdioData_Channel.
var (
	StdioData_Channel_name = map[int32]string{
		0: "INVALID",
		1: "STDOUT",
		2: "STDERR",
	}
	StdioData_Channel_value = map[string]int32{
		"INVALID": 0,
		"STDOUT":  1,
		"STDERR":  2,
	}
)

func (x StdioData_Channel) Enum() *StdioData_Channel {
	p := new(StdioData_Channel)
	*p = x
	return p
}

func (x StdioData_Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StdioData_Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_plugin_grpc_stdio_proto_enumTypes[0].Descriptor()
}

func (StdioData_Channel) Type() protoreflect.EnumType {
	return &file_internal_plugin_grpc_stdio_proto_enumTypes[0]
}

func (x StdioData_Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StdioData_Channel.Descriptor instead.
func (StdioData_Channel) EnumDescriptor() ([]byte, []int) {
	return file_internal_plugin_grpc_stdio_proto_rawDescGZIP(), []int{0, 0}
}

// StdioData is a single chunk of stdout or stderr data that is streamed
// from GRPCStdio.
type StdioData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       StdioData_Channel      `protobuf:"varint,1,opt,name=channel,proto3,enum=plugin.StdioData_Channel" json:"channel,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioData) Reset() {
	*x = StdioData{}
	mi := &file_internal_plugin_grpc_stdio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioData) ProtoMessage() {}

func (x *StdioData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_grpc_stdio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioData.ProtoReflect.Descriptor instead.
func (*StdioData) Descriptor() ([]byte, []int) {
	return file_internal_plugin_grpc_stdio_proto_rawDescGZIP(), []int{0}
}

func (x *StdioData) GetChannel() StdioData_Channel {
	if x != nil {
		return x.Channel
	}
	return StdioData_INVALID
}

func (x *StdioData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_plugin_grpc_stdio_proto protoreflect.FileDescriptor

const file_internal_plugin_grpc_stdio_proto_rawDesc = "" +
	"\n" +
	" internal/plugin/grpc_stdio.proto\x12\x06plugin\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n" +
	"\tStdioData\x123\n" +
	"\achannel\x18\x01 \x01(\x0e2\x19.plugin.StdioData.ChannelR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\".\n" +
	"\aChannel\x12\v\n" +
	"\aINVALID\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x022G\n" +
	"\tGRPCStdio\x12:\n" +
	"\vStreamStdio\x12\x16.google.protobuf.Empty\x1a\x11.plugin.StdioData0\x01B.Z,github.com/arloliu/go-plugin/internal/pluginb\x06proto3"

var (
	file_internal_plugin_grpc_stdio_proto_rawDescOnce sync.Once
	file_internal_plugin_grpc_stdio_proto_rawDescData []byte
)

func file_internal_plugin_grpc_stdio_proto_rawDescGZIP() []byte {
	file_internal_plugin_grpc_stdio_proto_rawDescOnce.Do(func() {
		file_internal_plugin_grpc_stdio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_grpc_stdio_proto_rawDesc), len(file_internal_plugin_grpc_stdio_proto_rawDesc)))
	})
	return file_internal_plugin_grpc_stdio_proto_rawDescData
}

var file_internal_plugin_grpc_stdio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_plugin_grpc_stdio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_plugin_grpc_stdio_proto_goTypes = []any{
	(StdioData_Channel)(0), // 0: plugin.StdioData.Channel
	(*StdioData)(nil),      // 1: plugin.StdioData
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_internal_plugin_grpc_stdio_proto_depIdxs = []int32{
	0, // 0: plugin.StdioData.channel:type_name -> plugin.StdioData.Channel
	2, // 1: plugin.GRPCStdio.StreamStdio:input_type -> google.protobuf.Empty
	1, // 2: plugin.GRPCStdio.StreamStdio:output_type -> plugin.StdioData
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_plugin_grpc_stdio_proto_init() }
func file_internal_plugin_grpc_stdio_proto_init() {
	if File_internal_plugin_grpc_stdio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_grpc_stdio_proto_rawDesc), len(file_internal_plugin_grpc_stdio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_grpc_stdio_proto_goTypes,
		DependencyIndexes: file_internal_plugin_grpc_stdio_proto_depIdxs,
		EnumInfos:         file_internal_plugin_grpc_stdio_proto_enumTypes,
		MessageInfos:      file_internal_plugin_grpc_stdio_proto_msgTypes,
	}.Build()
	File_internal_plugin_grpc_stdio_proto = out.File
	file_internal_plugin_grpc_stdio_proto_goTypes = nil
	file_internal_plugin_grpc_stdio_proto_depIdxs = nil
}
